
import "./globals.css";
import Link from "next/link";
import Header from "./header";
import Footer from "./footer";
// import { Providers } from "./redux/Providers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>vloerplaat</title>
      </head>
      <body >

          <Header/>
          <main className="p-5 bg-black text-white">
            {children}
          </main>
          <Footer/>

      </body>
    </html>
  );
}